config/routes.rb
Rails.application.routes.draw do
  get 'hello/index'
	root 'opportunities#index'
	resources :opportunities

end

app/models/opportunity.rb
class Opportunity < ActiveRecord::Base
	self.table_name = "salesforce.opportunity"
end

app/models/opportunity_stage.rb
class OpportunityStage < ActiveRecord::Base
	self.table_name = "salesforce.opportunitystage"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
  end
end

app/controllers/opportunities_controller.rb
class OpportunitiesController < ApplicationController

def create
  @opportunity = Opportunity.new(opportunity_params)

  if @opportunity.save
    redirect_to @opportunity
  else
    render 'new'
  end
end

def show
  @opportunity = Opportunity.find(params[:id])
end

def index
  @opportunities = Opportunity.all
end

def edit
  @opportunity = Opportunity.find(params[:id])
end

def update
  @opportunity = Opportunity.find(params[:id])

  if @opportunity.update(opportunity_params)
    redirect_to @opportunity
  else
    render 'edit'
  end
end

def destroy
  @opportunity = Opportunity.find(params[:id])
  @opportunity.destroy
 
  redirect_to opportunities_path
end

private
def opportunity_params
  params.require(:opportunity).permit(:name, :description, :amount, :closedate, :stagename)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/opportunities_helper.rb
module OpportunitiesHelper
end

app/views/hello/index.html.erb
<h1>Hello#index</h1>
<p>Find me in app/views/hello/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyProject3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/opportunities/edit.html.erb
<h1>Edit opportunity</h1>

<%= form_for :opportunity, url: opportunity_path(@opportunity), method: :patch do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </p>

  <p>
    <%= f.label :closedate %><br>
    <%= f.date_field :closedate %>
  </p>

  <p>
    <%= f.label :stagename %><br>
    <%= select(:opportunity, :stagename, OpportunityStage.all.collect {|os| os.masterlabel}) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', opportunities_path %>

app/views/opportunities/index.html.erb
<h1>Listing opportunities</h1>

<%= link_to 'New opportunity', new_opportunity_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Amount</th>
    <th>CloseDate</th>
    <th>StageName</th>
    <th colspan="2"></th>
  </tr>

  <% @opportunities.each do |opportunity| %>
    <tr>
      <td><%= opportunity.name %></td>
      <td><%= opportunity.amount %></td>
      <td><%= opportunity.closedate %></td>
      <td><%= opportunity.stagename %></td>
      <td><%= link_to 'Show', opportunity_path(opportunity) %></td>
      <td><%= link_to 'Edit', edit_opportunity_path(opportunity) %></td>
      <td><%= link_to 'Delete', opportunity_path(opportunity),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/opportunities/new.html.erb
<h1>New opportunity</h1>

<%= form_for :opportunity, url: opportunities_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </p>

  <p>
    <%= f.label :closedate %><br>
    <%= f.date_field :closedate %>
  </p>

  <p>
    <%= f.label :stagename %><br>
    <%= select(:opportunity, :stagename, OpportunityStage.all.collect {|os| os.masterlabel}) %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Back', opportunities_path %>

app/views/opportunities/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @opportunity.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @opportunity.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @opportunity.amount %>
</p>

<p>
  <strong>CloseDate:</strong>
  <%= @opportunity.closedate %>
</p>

<p>
  <strong>StageName:</strong>
  <%= @opportunity.stagename %>
</p>

<%= link_to 'Edit', edit_opportunity_path(@opportunity) %> | 
<%= link_to 'Back', opportunities_path %>